# Generated by Django 2.2.16 on 2022-11-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221106_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rewiew',
            new_name='review',
        ),
    ]
