# Generated by Django 2.2.16 on 2022-11-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221106_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='estimation',
            new_name='score',
        ),
    ]
